# Site settings
name: Joey Baruch
email: joey.baruch+contactme@gmail.com
#canonical_url: https://joeybaruch.com
keywords: >
 Software Engineer, Python, Scala, Java, Spark, Kafka, HDFS, Lambda Architecture, Near Real Time, Event Processing,
 DevOps, Bash, Git, Linux, Windows, Graph Databases, Distributed Computing, Natural Language Processing, NLP, Data Analytics,
 Machine Learning, Startups, Agile, Pair Programming, CI/CD
skills: "Senior Software Engineer in NYC, NY"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/joey-baruch-2930b97b/
  - title: stack-overflow
    url: https://stackoverflow.com/users/3517025/joey-baruch
  - title: medium
    url: https://medium.com/@jb2562
  - title: twitter
    url: https://twitter.com/JoeyBaruch2
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
